# Woodpecker CI Configuration
# Requires custom image: ./ci/build-image.sh --push

when:
  - event: pull_request
  - event: push
    branch: [main, master]
  - event: tag
  - event: cron
    cron: renovate

variables:
  - &ci_image jlipworth/stock-pitch-ci:latest

steps:
  - name: lint
    image: *ci_image
    commands:
      - ruff check src/ tests/ --output-format=github
      - ruff format --check src/ tests/

  - name: typecheck
    image: *ci_image
    commands:
      - mypy src/ --no-error-summary || true

  - name: test
    image: *ci_image
    depends_on: [lint]
    commands:
      - pytest -v --tb=short -m "not integration"

  - name: renovate
    image: renovate/renovate:latest
    when:
      - event: cron
        cron: renovate
    environment:
      RENOVATE_TOKEN:
        from_secret: github_token
    commands:
      - renovate --platform github --repositories jlipworth/stockpitch-study
