# Woodpecker CI Configuration
# Requires custom image: ./ci/build-image.sh --push

when:
  - event: pull_request
  - event: push
    branch: [main, master]
  - event: tag
  - event: cron
    cron: renovate

variables:
  - &ci_image jlipworth/stock-pitch-ci:latest

steps:
  - name: lint
    image: *ci_image
    pull: true
    environment:
      UV_PROJECT_ENVIRONMENT: /tmp/venv
    commands:
      - uv sync --frozen --only-group dev
      - /tmp/venv/bin/ruff check src/ tests/ --output-format=github
      - /tmp/venv/bin/ruff format --check src/ tests/

  - name: typecheck
    image: *ci_image
    pull: true
    environment:
      UV_PROJECT_ENVIRONMENT: /tmp/venv
    commands:
      - uv sync --frozen --only-group dev
      - MYPYPATH=src /tmp/venv/bin/mypy src/ --no-error-summary || true

  - name: test
    image: *ci_image
    pull: true
    depends_on: [lint]
    commands:
      # Use pre-built /opt/venv with CPU-only torch (no CUDA packages)
      - /opt/venv/bin/pytest tests/ -m "not integration" -v

  - name: renovate
    image: renovate/renovate:latest
    when:
      - event: cron
        cron: renovate
    environment:
      RENOVATE_TOKEN:
        from_secret: github_token
    commands:
      - renovate --platform github --repositories jlipworth/stockpitch-study

  - name: notify-success
    image: appleboy/drone-discord
    depends_on: [lint, typecheck, test]
    when:
      - status: success
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: >
        Build succeeded for {{repo.name}}
        Branch: {{commit.branch}}
        {{build.link}}

  - name: notify-failure
    image: appleboy/drone-discord
    depends_on: [lint, typecheck, test]
    when:
      - status: failure
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: >
        Build failed for {{repo.name}}
        Branch: {{commit.branch}}
        {{build.link}}
